CREATE TABLE Bahnhof(
	idBahnhof INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    City VARCHAR(45) NOT NULL,
    BahnhofName VARCHAR(45) NOT NULL
);
CREATE TABLE Bahnsteig(
	idBahnsteig INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BahnsteigName VARCHAR(45) NOT NULL,
    idBahnhof INT NOT NULL
);
CREATE TABLE Ankunft(
	idAnkunft INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DatumUhrzeit DATETIME NOT NULL,
    idZug INT NOT NULL,
    idBahnsteig INT NOT NULL
);
CREATE TABLE Abfahrt(
	idAbfahrt INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DatumUhrzeit DATETIME NOT NULL,
    idZug INT NOT NULL,
    idBahnsteig INT NOT NULL
);
CREATE TABLE Zug(
	Zugnummer INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ZugName VARCHAR(45) NOT NULL,
    ZugTyp VARCHAR(10) NOT NULL,
    idAnkunft INT NOT NULL,
    idAbfahrt INT NOT NULL
);



